name: import from web interface
on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Your Mastodon server. If you are dbatools@dataplatform.social, this would be dataplatform.social.'
        required: true
      file-path:
        description: 'The path to the CSV file, using runtime parameters pretty much means you will be specifying a web address.'
        required: true
jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Import from CSV or zip
        uses: potatoqualitee/influx@main
        with:
          server: '${{ github.event.inputs.server }}'
          file-path: '${{ github.event.inputs.file-path }}'
        env:
          ACCESS_TOKEN: "${{ secrets.ACCESS_TOKEN }}"